Add --cli option
rzc0d3r/ESET-KeyGen pull request #35
Opened 2023-11-18 10:52 UTC by AdityaGarg8

This allows running this on cli like github actions by eliminating the need to use `--cli` argument.

2023-11-18 11:33 UTC, rzc0d3r commented
Maybe it would be better to make a argument that disables all input('Run anyway?') and etc similar commands?

2023-11-18 13:00 UTC, AdityaGarg8 commented
Maybe use `--no-input`. Also, I hope the 2 enter commands addressed in this PR are the only inputs?

2023-11-18 13:40 UTC, rzc0d3r commented
Yes, from a specific :

https://github.com/rzc0d3r/ESET-KeyGen/blob/main/main.py#L42

https://github.com/rzc0d3r/ESET-KeyGen/blob/main/main.py#L54

Argument disabling this: --force

2023-11-18 15:43 UTC, AdityaGarg8 commented
Changed

2023-11-18 16:51 UTC, rzc0d3r commented
Great, but the error output needs to be left in. How will people copy the Traceback and send it to me? They will have to run the project in the console, not just click on it in explorer.

2023-11-18 16:55 UTC, rzc0d3r commented
I have a test version with Traceback output and new JavaScript code lying around on my PC. But I need to test it well.

2023-11-18 16:57 UTC, AdityaGarg8 commented
My main reason for this PR was for using GitHub actions. Makes it easier and much safer to get licenses without the risk of getting banned.

2023-11-18 16:59 UTC, rzc0d3r commented
> Great, but the error output needs to be left in. How will people copy the Traceback and send it to me? They will have to run the project in the console, not just click on it in explorer.

Oh. Well, if they run it from explorer, then --force will not be passed and then the project will run with user input.

2023-11-18 17:01 UTC, AdityaGarg8 commented
Yes exactly.

2023-11-18 21:33 UTC, rzc0d3r requested changes
Don't touch the Press Enter line... at the end of the file

2023-11-19 04:19 UTC, AdityaGarg8 commented
> Don't touch the Press Enter line... at the end of the file

This shall fail runs on CIs.

2023-11-19 06:43 UTC, AdityaGarg8 commented
If I remove the requirements of pressing enter, I can generate license using GitHub actions like this:

https://github.com/AdityaGarg8/random/actions/runs/6918918950

2023-11-19 13:02 UTC, rzc0d3r commented
Sorry I just don't know how github cli works. Is your commit fully working? If so, I'll merge it.

2023-11-19 13:03 UTC, AdityaGarg8 commented
Yes, if I remove the need of pressing enter

2023-11-19 13:04 UTC, AdityaGarg8 commented
If you want, I can help you to get a GitHub CI on your repo to generate licenses

2023-11-19 13:08 UTC, rzc0d3r commented
> If you want, I can help you to get a GitHub CI on your repo to generate licenses

What features does it add? I've never encountered this in my life..

2023-11-19 13:10 UTC, AdityaGarg8 commented
Just like the link I sent you, If you run this manually, it shall use your scripts and generate a license key and display it. Although, I doubt it shall be needed in your repo. I just asked, in case you wanted help.

2023-11-19 13:19 UTC, rzc0d3r commented
I understand that through Actions you can run the project in code space and get the results directly on github? Without having to do everything on the main system?

2023-11-19 13:20 UTC, AdityaGarg8 commented
Yes

2023-11-19 13:23 UTC, rzc0d3r commented
It's not a bad feature. Can people who don't have a github account do the same?

2023-11-19 13:24 UTC, AdityaGarg8 commented
No. The person has to fork your repo or you have generate the license on your repo.

2023-11-19 13:26 UTC, rzc0d3r commented
What kind of license?

2023-11-19 13:27 UTC, AdityaGarg8 commented
I meant the license key

2023-11-19 13:30 UTC, rzc0d3r commented
Well, I don't think that's necessary just yet. Idk

2023-11-19 13:31 UTC, rzc0d3r commented
Because it looks pretty complicated. And this will need to be described in the documentation

2023-11-19 13:31 UTC, AdityaGarg8 commented
Fair enough. I hope we can come to some decision on this PR?

2023-11-19 13:33 UTC, rzc0d3r commented
> Fair enough. I hope we can come to some decision on this PR?

I could approve. But what's the next step?

2023-11-19 13:34 UTC, AdityaGarg8 commented
Well, in my case, I'll create a GitHub CI in my private repo, which shall clone your repo, and generate a license key. I'll run the workflow whenever my license expires.

2023-11-19 13:35 UTC, AdityaGarg8 commented
Something like this https://github.com/AdityaGarg8/random/blob/main/.github/workflows/GenerateChecksum.yml

2023-11-19 13:35 UTC, AdityaGarg8 commented
Although it needs some cleanup

2023-11-19 13:38 UTC, rzc0d3r approved these changes

2023-11-19 13:39 UTC, merged

2023-11-19 13:39 UTC, AdityaGarg8 commented on main.py
> +    input('Press Enter...')
This needs to be addressed

2023-11-19 13:40 UTC, AdityaGarg8 commented
Oh it got merged.

2023-11-19 13:52 UTC, AdityaGarg8 commented
> Oh it got merged.

Now it got reverted?

2023-11-19 13:55 UTC, rzc0d3r commented
> > Oh it got merged.
> 
> Now it got reverted?

Lmao. I made the mistake of merging the code. I had to return the return. Don't worry, your code is already in the project.

2023-11-19 13:56 UTC, rzc0d3r commented
For cli to work consistently, do you need to remove input('Press Enter...') at the end of main.py?

2023-11-19 13:57 UTC, AdityaGarg8 commented
Your forgot to address this line https://github.com/rzc0d3r/ESET-KeyGen/blob/main/main.py#L103

2023-11-19 13:57 UTC, AdityaGarg8 commented
> For cli to work consistently, do you need to remove input('Press Enter...') at the end of main.py?

Yes

2023-11-19 13:58 UTC, AdityaGarg8 commented
Is there any solid reason to not remove the last line though, maybe I could help there?

2023-11-19 13:58 UTC, rzc0d3r commented
I can add the --cli key and then it will disable all inputs.

2023-11-19 13:59 UTC, AdityaGarg8 commented
Cool

2023-11-19 14:00 UTC, AdityaGarg8 commented
Also, thanks a lot for this project. Saved me a couple of bucks:)

2023-11-19 14:13 UTC, rzc0d3r commented
> Also, thanks a lot for this project. Saved me a couple of bucks:)

https://github.com/rzc0d3r/ESET-KeyGen/commit/e8658a66dac5d36300e85ec11d4ec26109593b3b. You're welcome. Thank you.